SHOW COMPUTE POOL INSTANCE FAMILIES;

USE ROLE ACCOUNTADMIN;

CREATE COMPUTE POOL my_trial_pool
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 600;

DESCRIBE COMPUTE POOL MY_TRIAL_POOL;